[package]
name = "minus_games_gui"
version = "0.4.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", branch = "master", features = ["image", "tokio"] }
reqwest = { version = "0", features = ["json", "cookies", "brotli", "gzip", "multipart", "blocking", "stream"] }
dotenvy = "0"
dirs = "5"
tracing = "0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
minus_games_client = { path = "../minus_games_client" }
minus_games_models = { path = "../minus_games_models" }
tokio = { version = "1", features = ["full"] }
